site_name: SQC
site_url: https://hephy-dd.github.io/sqc/
repo_url: https://github.com/hephy-dd/sqc/
edit_uri: edit/main/docs/
site_description: Sensor Quality Control for the CMS Tracker
site_author: HEPHY
copyright: "Copyright &copy; 2022-2024 <a href=\"https://hephy.at/\">HEPHY</a>. SQC is licensed under the <a href=\"https://github.com/hephy-dd/sqc/tree/main/LICENSE\">GNU General Public License Version 3</a>."
nav:
    - Home: index.md
    - instruments.md
    - Measurements:
        - measurements/iv.md
        - measurements/cv.md
        - measurements/stripscan.md
        - measurements/rpoly.md
        - measurements/istrip.md
        - measurements/idiel.md
        - measurements/cac.md
        - measurements/cint.md
        - measurements/rint.md
        - measurements/idark.md

markdown_extensions:
    - smarty
extra:
    version: 0.10.0
theme:
    name: readthedocs
    locale: en
