name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs==1.3.*

      - name: Build
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --strict --force
